/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API audit by ID */
        get: operations["get-api-audit-by-id"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/balance-adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API balance adjustments */
        get: operations["get-api-balance-adjustments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/balance-observations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API balance observations */
        get: operations["get-api-balance-observations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buying-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API buying intents */
        get: operations["get-api-buying-intents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API dashboard */
        get: operations["get-api-dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API expenses */
        get: operations["get-api-expenses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/income": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API income */
        get: operations["get-api-income"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API projects by ID report */
        get: operations["get-api-projects-by-id-report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receivables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API receivables */
        get: operations["get-api-receivables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/repayments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API repayments */
        get: operations["get-api-repayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API reports monthly */
        get: operations["get-api-reports-monthly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API transfers */
        get: operations["get-api-transfers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            archived: boolean;
            balance: string;
            balance_quality: string;
            currency: string;
            /** Format: int64 */
            estimated_expense_count: number;
            id: string;
            name: string;
            opening_amount: string;
            opening_date: string;
            /** Format: int64 */
            unresolved_expense_count: number;
            /** Format: int64 */
            version?: number;
        };
        Allocation: {
            amount: string;
            category_id: string;
            project_id?: string;
        };
        AllocationTotal: {
            amount: string;
            category_id: string;
            currency: string;
            project_id: string;
        };
        AuditEntry: {
            action: string;
            client_name: string;
            client_version: string;
            entity_id: string;
            /** Format: int64 */
            id: number;
            operation_key: string;
            recorded_at: string;
            request_id: string;
            snapshot: {
                [key: string]: unknown;
            };
            source: string;
        };
        AuditOutput: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AuditOutput.json
             */
            readonly $schema?: string;
            entries: components["schemas"]["AuditEntry"][] | null;
        };
        BalanceAdjustment: {
            account_id: string;
            amount: string;
            currency: string;
            date: string;
            id: string;
            observation_id: string;
            reason: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        BalanceAdjustmentPage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BalanceAdjustmentPage.json
             */
            readonly $schema?: string;
            adjustments: components["schemas"]["BalanceAdjustment"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        BalanceObservation: {
            account_id: string;
            actual_balance: string;
            as_of_date: string;
            balance_quality: string;
            basis: string;
            currency: string;
            current_ledger_balance: string;
            difference: string;
            /** Format: int64 */
            estimated_expense_count: number;
            id: string;
            notes: string;
            recorded_ledger_balance: string;
            status: string;
            /** Format: int64 */
            unresolved_expense_count: number;
            /** Format: int64 */
            version: number;
        };
        BalanceObservationPage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BalanceObservationPage.json
             */
            readonly $schema?: string;
            observations: components["schemas"]["BalanceObservation"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        BuyingIntent: {
            candidate_id?: string;
            candidates: components["schemas"]["IntentCandidate"][] | null;
            expense?: components["schemas"]["Expense"];
            id: string;
            notes: string;
            outcome_note: string;
            status: string;
            title: string;
            /** Format: int64 */
            version: number;
        };
        BuyingIntentPage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BuyingIntentPage.json
             */
            readonly $schema?: string;
            intents: components["schemas"]["BuyingIntent"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        ConversionEvidence: {
            effective_at: string;
            rate: string;
            reference?: string;
            retrieved_at: string;
            source: string;
        };
        CurrencyTotal: {
            amount: string;
            currency: string;
        };
        Dashboard: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/Dashboard.json
             */
            readonly $schema?: string;
            accounts: components["schemas"]["Account"][] | null;
            categories: components["schemas"]["Named"][] | null;
            expenses: components["schemas"]["Expense"][] | null;
            projects: components["schemas"]["Named"][] | null;
            spending: components["schemas"]["Spending"][] | null;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Expense: {
            account_id: string;
            allocations: components["schemas"]["Allocation"][] | null;
            amount: string;
            currency: string;
            date: string;
            description: string;
            id: string;
            payment: components["schemas"]["ExpensePayment"];
            status: string;
            /** Format: int64 */
            version: number;
        };
        ExpensePage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ExpensePage.json
             */
            readonly $schema?: string;
            expenses: components["schemas"]["Expense"][] | null;
            matching_allocation_totals: components["schemas"]["AllocationTotal"][] | null;
            /** Format: int64 */
            total_count: number;
            totals: components["schemas"]["CurrencyTotal"][] | null;
        };
        ExpensePayment: {
            amount?: string;
            currency: string;
            evidence?: components["schemas"]["ConversionEvidence"];
            state: string;
        };
        Income: {
            account_id: string;
            amount: string;
            currency: string;
            date: string;
            description: string;
            id: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        IncomePage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/IncomePage.json
             */
            readonly $schema?: string;
            incomes: components["schemas"]["Income"][] | null;
            /** Format: int64 */
            total_count: number;
            totals: components["schemas"]["CurrencyTotal"][] | null;
        };
        IntentCandidate: {
            advertised_amount?: string;
            currency?: string;
            id: string;
            notes: string;
            reference: string;
        };
        MonthlyAccountMovement: {
            account_id: string;
            adjustments: string;
            balance_quality: string;
            currency: string;
            /** Format: int64 */
            estimated_expense_count: number;
            expense_debits: string;
            income: string;
            name: string;
            net_change: string;
            repayments: string;
            transfer_in: string;
            transfer_out: string;
            /** Format: int64 */
            unresolved_expense_count: number;
        };
        MonthlyAllocationTotal: {
            amount: string;
            currency: string;
            id: string;
            name: string;
        };
        MonthlyReport: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/MonthlyReport.json
             */
            readonly $schema?: string;
            account_id?: string;
            accounts: components["schemas"]["MonthlyAccountMovement"][] | null;
            category_totals: components["schemas"]["MonthlyAllocationTotal"][] | null;
            from_date: string;
            income_totals: components["schemas"]["CurrencyTotal"][] | null;
            month: string;
            project_totals: components["schemas"]["MonthlyAllocationTotal"][] | null;
            spending_totals: components["schemas"]["CurrencyTotal"][] | null;
            to_date: string;
        };
        Named: {
            archived: boolean;
            id: string;
            name: string;
            /** Format: int64 */
            version?: number;
        };
        ProjectReport: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ProjectReport.json
             */
            readonly $schema?: string;
            category_totals: components["schemas"]["AllocationTotal"][] | null;
            from_date?: string;
            history: components["schemas"]["ExpensePage"];
            project: components["schemas"]["Named"];
            spending_totals: components["schemas"]["CurrencyTotal"][] | null;
            to_date?: string;
        };
        Receivable: {
            amount: string;
            currency: string;
            debtor: string;
            due_date?: string;
            id: string;
            notes: string;
            remaining_amount: string;
            repaid_amount: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        ReceivablePage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReceivablePage.json
             */
            readonly $schema?: string;
            outstanding_totals: components["schemas"]["CurrencyTotal"][] | null;
            receivables: components["schemas"]["Receivable"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        Repayment: {
            account_id: string;
            amount: string;
            currency: string;
            date: string;
            description: string;
            id: string;
            receivable_id: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        RepaymentPage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RepaymentPage.json
             */
            readonly $schema?: string;
            repayments: components["schemas"]["Repayment"][] | null;
            /** Format: int64 */
            total_count: number;
        };
        Spending: {
            amount: string;
            currency: string;
            project_id: string;
            project_name: string;
        };
        Transfer: {
            date: string;
            description: string;
            destination_account_id: string;
            destination_amount: string;
            destination_currency: string;
            id: string;
            source_account_id: string;
            source_amount: string;
            source_currency: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        TransferPage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/TransferPage.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            total_count: number;
            transfers: components["schemas"]["Transfer"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-api-audit-by-id": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditOutput"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-balance-adjustments": {
        parameters: {
            query?: {
                account_id?: string;
                observation_id?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceAdjustmentPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-balance-observations": {
        parameters: {
            query?: {
                account_id?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceObservationPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-buying-intents": {
        parameters: {
            query?: {
                search?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuyingIntentPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-expenses": {
        parameters: {
            query?: {
                payment_state?: string;
                account_id?: string;
                currency?: string;
                from_date?: string;
                to_date?: string;
                category_id?: string;
                project_id?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpensePage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-income": {
        parameters: {
            query?: {
                account_id?: string;
                currency?: string;
                from_date?: string;
                to_date?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomePage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-projects-by-id-report": {
        parameters: {
            query?: {
                from_date?: string;
                to_date?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectReport"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-receivables": {
        parameters: {
            query?: {
                status?: string;
                currency?: string;
                debtor?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceivablePage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-repayments": {
        parameters: {
            query?: {
                receivable_id?: string;
                account_id?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepaymentPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-reports-monthly": {
        parameters: {
            query: {
                month: string;
                account_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyReport"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-api-transfers": {
        parameters: {
            query?: {
                account_id?: string;
                from_date?: string;
                to_date?: string;
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferPage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
