// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           string
	Name         string
	Currency     string
	Scale        int16
	OpeningMinor int64
	OpeningDate  pgtype.Date
	Version      int64
	Archived     bool
}

type Allocation struct {
	ExpenseID   string
	Ordinal     int32
	AmountMinor int64
	CategoryID  string
	ProjectID   pgtype.Text
}

type AuditEntry struct {
	ID            int64
	EntityID      string
	Action        string
	RecordedAt    pgtype.Timestamptz
	Snapshot      []byte
	Source        string
	OperationKey  string
	RequestID     string
	ClientName    string
	ClientVersion string
}

type BalanceAdjustment struct {
	ID            string
	ObservationID string
	AccountID     string
	AmountMinor   int64
	OccurredDate  pgtype.Date
	Reason        string
	Status        string
	Version       int64
}

type BalanceObservation struct {
	ID                  string
	AccountID           string
	AsOfDate            pgtype.Date
	ActualMinor         int64
	RecordedLedgerMinor pgtype.Numeric
	Basis               string
	Notes               string
	Status              string
	Version             int64
}

type BuyingIntent struct {
	ID          string
	CreatedAt   pgtype.Timestamptz
	Title       string
	Notes       string
	Status      string
	Version     int64
	CandidateID pgtype.Text
	OutcomeNote string
	ExpenseID   pgtype.Text
}

type Category struct {
	ID       string
	Name     string
	Version  int64
	Archived bool
}

type Currency struct {
	Code  string
	Scale int16
}

type Expense struct {
	ID                 string
	AccountID          string
	AmountMinor        int64
	OccurredDate       pgtype.Date
	Description        string
	Version            int64
	Status             string
	Currency           string
	DebitMinor         pgtype.Int8
	DebitState         string
	ConversionEvidence []byte
}

type Income struct {
	ID           string
	AccountID    string
	AmountMinor  int64
	OccurredDate pgtype.Date
	Description  string
	Version      int64
	Status       string
}

type IntentCandidate struct {
	ID              string
	CreatedAt       pgtype.Timestamptz
	IntentID        string
	Reference       string
	Notes           string
	AdvertisedMinor pgtype.Int8
	Currency        pgtype.Text
}

type OperationResult struct {
	OperationKey string
	Operation    string
	Payload      []byte
	Result       []byte
}

type Project struct {
	ID       string
	Name     string
	Version  int64
	Archived bool
}

type Receivable struct {
	ID          string
	Debtor      string
	AmountMinor int64
	Currency    string
	DueDate     pgtype.Date
	Notes       string
	Version     int64
	Status      string
	CreatedAt   pgtype.Timestamptz
}

type Repayment struct {
	ID           string
	ReceivableID string
	AccountID    string
	AmountMinor  int64
	OccurredDate pgtype.Date
	Description  string
	Version      int64
	Status       string
}

type Transfer struct {
	ID                   string
	SourceAccountID      string
	DestinationAccountID string
	SourceMinor          int64
	DestinationMinor     int64
	OccurredDate         pgtype.Date
	Description          string
	Version              int64
	Status               string
}
