// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalanceAsOf = `-- name: AccountBalanceAsOf :one
SELECT (a.opening_minor::numeric
-COALESCE((SELECT sum(debit_minor) FROM expenses WHERE account_id=a.id AND status='posted' AND occurred_date<=$1::text::date),0)
+COALESCE((SELECT sum(amount_minor) FROM incomes WHERE account_id=a.id AND status='posted' AND occurred_date<=$1::text::date),0)
-COALESCE((SELECT sum(source_minor) FROM transfers WHERE source_account_id=a.id AND status='posted' AND occurred_date<=$1::text::date),0)
+COALESCE((SELECT sum(destination_minor) FROM transfers WHERE destination_account_id=a.id AND status='posted' AND occurred_date<=$1::text::date),0)
+COALESCE((SELECT sum(amount_minor) FROM repayments WHERE account_id=a.id AND status='posted' AND occurred_date<=$1::text::date),0)
+COALESCE((SELECT sum(amount_minor) FROM balance_adjustments WHERE account_id=a.id AND status='posted' AND occurred_date<=$1::text::date),0))::text AS balance
FROM accounts a WHERE a.id=$2
`

type AccountBalanceAsOfParams struct {
	AsOfDate  string
	AccountID string
}

func (q *Queries) AccountBalanceAsOf(ctx context.Context, arg AccountBalanceAsOfParams) (string, error) {
	row := q.db.QueryRow(ctx, accountBalanceAsOf, arg.AsOfDate, arg.AccountID)
	var balance string
	err := row.Scan(&balance)
	return balance, err
}

const accountBalances = `-- name: AccountBalances :many
SELECT a.id,a.name,a.currency,a.opening_minor,a.opening_date::text AS opening_date,a.version,a.archived,
(a.opening_minor::numeric-COALESCE(e.amount,0)+COALESCE(i.amount,0)-COALESCE(t_out.amount,0)+COALESCE(t_in.amount,0)+COALESCE(r.amount,0)+COALESCE(ba.amount,0))::text AS balance,COALESCE(e.estimated_count,0)::bigint AS estimated_count,COALESCE(e.unresolved_count,0)::bigint AS unresolved_count
FROM accounts a
LEFT JOIN (SELECT account_id,sum(debit_minor) AS amount,count(*) FILTER(WHERE debit_state='estimated') AS estimated_count,count(*) FILTER(WHERE debit_state='unresolved') AS unresolved_count FROM expenses WHERE status='posted' GROUP BY account_id) e ON e.account_id=a.id
LEFT JOIN (SELECT account_id,sum(amount_minor) AS amount FROM incomes WHERE status='posted' GROUP BY account_id) i ON i.account_id=a.id
LEFT JOIN (SELECT source_account_id,sum(source_minor) AS amount FROM transfers WHERE status='posted' GROUP BY source_account_id) t_out ON t_out.source_account_id=a.id
LEFT JOIN (SELECT destination_account_id,sum(destination_minor) AS amount FROM transfers WHERE status='posted' GROUP BY destination_account_id) t_in ON t_in.destination_account_id=a.id
LEFT JOIN (SELECT account_id,sum(amount_minor) AS amount FROM repayments WHERE status='posted' GROUP BY account_id) r ON r.account_id=a.id
LEFT JOIN (SELECT account_id,sum(amount_minor) AS amount FROM balance_adjustments WHERE status='posted' GROUP BY account_id) ba ON ba.account_id=a.id
ORDER BY a.name,a.id
`

type AccountBalancesRow struct {
	ID              string
	Name            string
	Currency        string
	OpeningMinor    int64
	OpeningDate     string
	Version         int64
	Archived        bool
	Balance         string
	EstimatedCount  int64
	UnresolvedCount int64
}

func (q *Queries) AccountBalances(ctx context.Context) ([]AccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, accountBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBalancesRow
	for rows.Next() {
		var i AccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.OpeningMinor,
			&i.OpeningDate,
			&i.Version,
			&i.Archived,
			&i.Balance,
			&i.EstimatedCount,
			&i.UnresolvedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const audit = `-- name: Audit :many
SELECT id,entity_id,action,to_char(recorded_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"')::text AS recorded_at,snapshot,source,operation_key,request_id,client_name,client_version FROM audit_entries WHERE entity_id=$1 ORDER BY id
`

type AuditRow struct {
	ID            int64
	EntityID      string
	Action        string
	RecordedAt    string
	Snapshot      []byte
	Source        string
	OperationKey  string
	RequestID     string
	ClientName    string
	ClientVersion string
}

func (q *Queries) Audit(ctx context.Context, entityID string) ([]AuditRow, error) {
	rows, err := q.db.Query(ctx, audit, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditRow
	for rows.Next() {
		var i AuditRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.Action,
			&i.RecordedAt,
			&i.Snapshot,
			&i.Source,
			&i.OperationKey,
			&i.RequestID,
			&i.ClientName,
			&i.ClientVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpBalanceObservation = `-- name: BumpBalanceObservation :exec
UPDATE balance_observations SET version=version+1 WHERE id=$1
`

func (q *Queries) BumpBalanceObservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpBalanceObservation, id)
	return err
}

const bumpBuyingIntent = `-- name: BumpBuyingIntent :exec
UPDATE buying_intents SET version=version+1 WHERE id=$1
`

func (q *Queries) BumpBuyingIntent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpBuyingIntent, id)
	return err
}

const bumpReceivable = `-- name: BumpReceivable :exec
UPDATE receivables SET version=version+1 WHERE id=$1
`

func (q *Queries) BumpReceivable(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, bumpReceivable, id)
	return err
}

const cancelBuyingIntent = `-- name: CancelBuyingIntent :exec
UPDATE buying_intents SET status='cancelled',outcome_note=$2,version=version+1 WHERE id=$1
`

type CancelBuyingIntentParams struct {
	ID          string
	OutcomeNote string
}

func (q *Queries) CancelBuyingIntent(ctx context.Context, arg CancelBuyingIntentParams) error {
	_, err := q.db.Exec(ctx, cancelBuyingIntent, arg.ID, arg.OutcomeNote)
	return err
}

const categories = `-- name: Categories :many
SELECT id,name,version,archived FROM categories ORDER BY name,id
`

func (q *Queries) Categories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, categories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countBuyingIntents = `-- name: CountBuyingIntents :one
SELECT count(*) FROM buying_intents WHERE ($1::text='all' OR status=$1::text) AND ($2::text='' OR strpos(lower(title),lower($2::text))>0 OR strpos(lower(notes),lower($2::text))>0)
`

type CountBuyingIntentsParams struct {
	Status string
	Search string
}

func (q *Queries) CountBuyingIntents(ctx context.Context, arg CountBuyingIntentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBuyingIntents, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllocations = `-- name: DeleteAllocations :exec
DELETE FROM allocations WHERE expense_id=$1
`

func (q *Queries) DeleteAllocations(ctx context.Context, expenseID string) error {
	_, err := q.db.Exec(ctx, deleteAllocations, expenseID)
	return err
}

const expenseBalanceQualityAsOf = `-- name: ExpenseBalanceQualityAsOf :one
SELECT count(*) FILTER(WHERE debit_state='estimated') AS estimated_count,count(*) FILTER(WHERE debit_state='unresolved') AS unresolved_count FROM expenses WHERE account_id=$1 AND status='posted' AND occurred_date<=$2::text::date
`

type ExpenseBalanceQualityAsOfParams struct {
	AccountID string
	AsOfDate  string
}

type ExpenseBalanceQualityAsOfRow struct {
	EstimatedCount  int64
	UnresolvedCount int64
}

func (q *Queries) ExpenseBalanceQualityAsOf(ctx context.Context, arg ExpenseBalanceQualityAsOfParams) (ExpenseBalanceQualityAsOfRow, error) {
	row := q.db.QueryRow(ctx, expenseBalanceQualityAsOf, arg.AccountID, arg.AsOfDate)
	var i ExpenseBalanceQualityAsOfRow
	err := row.Scan(&i.EstimatedCount, &i.UnresolvedCount)
	return i, err
}

const filteredAllocationTotals = `-- name: FilteredAllocationTotals :many
SELECT l.category_id,COALESCE(l.project_id,'')::text AS project_id,e.currency,sum(l.amount_minor)::text AS amount
FROM expenses e JOIN accounts a ON a.id=e.account_id JOIN allocations l ON l.expense_id=e.id
WHERE ($1::text='' OR e.account_id=$1)
AND ($2::text='' OR e.currency=$2)
AND ($3::text='' OR e.debit_state=$3 OR ($3::text='needs_attention' AND e.debit_state IN ('estimated','unresolved')))
AND ($4::text='' OR e.occurred_date>=NULLIF($4::text,'')::date)
AND ($5::text='' OR e.occurred_date<=NULLIF($5::text,'')::date)
AND ($6::text='all' OR e.status=$6)
AND EXISTS(SELECT 1 FROM allocations l WHERE l.expense_id=e.id
 AND ($7::text='' OR l.category_id=$7)
 AND ($8::text='' OR l.project_id=$8))
AND e.status='posted'
AND ($7::text='' OR l.category_id=$7)
AND ($8::text='' OR l.project_id=$8)
GROUP BY l.category_id,l.project_id,e.currency ORDER BY l.category_id,l.project_id,e.currency
`

type FilteredAllocationTotalsParams struct {
	AccountID    string
	Currency     string
	PaymentState string
	FromDate     string
	ToDate       string
	Status       string
	CategoryID   string
	ProjectID    string
}

type FilteredAllocationTotalsRow struct {
	CategoryID string
	ProjectID  string
	Currency   string
	Amount     string
}

func (q *Queries) FilteredAllocationTotals(ctx context.Context, arg FilteredAllocationTotalsParams) ([]FilteredAllocationTotalsRow, error) {
	rows, err := q.db.Query(ctx, filteredAllocationTotals,
		arg.AccountID,
		arg.Currency,
		arg.PaymentState,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.CategoryID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilteredAllocationTotalsRow
	for rows.Next() {
		var i FilteredAllocationTotalsRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.ProjectID,
			&i.Currency,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredBalanceAdjustmentCount = `-- name: FilteredBalanceAdjustmentCount :one
SELECT count(*) FROM balance_adjustments WHERE ($1::text='' OR account_id=$1) AND ($2::text='' OR observation_id=$2) AND ($3::text='all' OR status=$3)
`

type FilteredBalanceAdjustmentCountParams struct {
	AccountID     string
	ObservationID string
	Status        string
}

func (q *Queries) FilteredBalanceAdjustmentCount(ctx context.Context, arg FilteredBalanceAdjustmentCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredBalanceAdjustmentCount, arg.AccountID, arg.ObservationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredBalanceAdjustmentIDs = `-- name: FilteredBalanceAdjustmentIDs :many
SELECT id FROM balance_adjustments WHERE ($1::text='' OR account_id=$1) AND ($2::text='' OR observation_id=$2) AND ($3::text='all' OR status=$3) ORDER BY occurred_date DESC,id DESC LIMIT $5::bigint OFFSET $4::bigint
`

type FilteredBalanceAdjustmentIDsParams struct {
	AccountID     string
	ObservationID string
	Status        string
	PageOffset    int64
	PageLimit     int64
}

func (q *Queries) FilteredBalanceAdjustmentIDs(ctx context.Context, arg FilteredBalanceAdjustmentIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredBalanceAdjustmentIDs,
		arg.AccountID,
		arg.ObservationID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredBalanceObservationCount = `-- name: FilteredBalanceObservationCount :one
SELECT count(*) FROM balance_observations WHERE ($1::text='' OR account_id=$1)
`

func (q *Queries) FilteredBalanceObservationCount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, filteredBalanceObservationCount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredBalanceObservationIDs = `-- name: FilteredBalanceObservationIDs :many
SELECT id FROM balance_observations WHERE ($1::text='' OR account_id=$1) ORDER BY as_of_date DESC,id DESC LIMIT $3::bigint OFFSET $2::bigint
`

type FilteredBalanceObservationIDsParams struct {
	AccountID  string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) FilteredBalanceObservationIDs(ctx context.Context, arg FilteredBalanceObservationIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredBalanceObservationIDs, arg.AccountID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredExpenseCount = `-- name: FilteredExpenseCount :one
SELECT count(*)
FROM expenses e JOIN accounts a ON a.id=e.account_id
WHERE ($1::text='' OR e.account_id=$1)
AND ($2::text='' OR e.currency=$2)
AND ($3::text='' OR e.debit_state=$3 OR ($3::text='needs_attention' AND e.debit_state IN ('estimated','unresolved')))
AND ($4::text='' OR e.occurred_date>=NULLIF($4::text,'')::date)
AND ($5::text='' OR e.occurred_date<=NULLIF($5::text,'')::date)
AND ($6::text='all' OR e.status=$6)
AND EXISTS(SELECT 1 FROM allocations l WHERE l.expense_id=e.id
 AND ($7::text='' OR l.category_id=$7)
 AND ($8::text='' OR l.project_id=$8))
`

type FilteredExpenseCountParams struct {
	AccountID    string
	Currency     string
	PaymentState string
	FromDate     string
	ToDate       string
	Status       string
	CategoryID   string
	ProjectID    string
}

func (q *Queries) FilteredExpenseCount(ctx context.Context, arg FilteredExpenseCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredExpenseCount,
		arg.AccountID,
		arg.Currency,
		arg.PaymentState,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.CategoryID,
		arg.ProjectID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredExpenseIDs = `-- name: FilteredExpenseIDs :many
SELECT e.id
FROM expenses e JOIN accounts a ON a.id=e.account_id
WHERE ($1::text='' OR e.account_id=$1)
AND ($2::text='' OR e.currency=$2)
AND ($3::text='' OR e.debit_state=$3 OR ($3::text='needs_attention' AND e.debit_state IN ('estimated','unresolved')))
AND ($4::text='' OR e.occurred_date>=NULLIF($4::text,'')::date)
AND ($5::text='' OR e.occurred_date<=NULLIF($5::text,'')::date)
AND ($6::text='all' OR e.status=$6)
AND EXISTS(SELECT 1 FROM allocations l WHERE l.expense_id=e.id
 AND ($7::text='' OR l.category_id=$7)
 AND ($8::text='' OR l.project_id=$8))
ORDER BY e.occurred_date DESC,e.id DESC LIMIT $10::bigint OFFSET $9::bigint
`

type FilteredExpenseIDsParams struct {
	AccountID    string
	Currency     string
	PaymentState string
	FromDate     string
	ToDate       string
	Status       string
	CategoryID   string
	ProjectID    string
	PageOffset   int64
	PageLimit    int64
}

func (q *Queries) FilteredExpenseIDs(ctx context.Context, arg FilteredExpenseIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredExpenseIDs,
		arg.AccountID,
		arg.Currency,
		arg.PaymentState,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.CategoryID,
		arg.ProjectID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredExpenseTotals = `-- name: FilteredExpenseTotals :many
SELECT e.currency,sum(e.amount_minor)::text AS amount
FROM expenses e JOIN accounts a ON a.id=e.account_id
WHERE ($1::text='' OR e.account_id=$1)
AND ($2::text='' OR e.currency=$2)
AND ($3::text='' OR e.debit_state=$3 OR ($3::text='needs_attention' AND e.debit_state IN ('estimated','unresolved')))
AND ($4::text='' OR e.occurred_date>=NULLIF($4::text,'')::date)
AND ($5::text='' OR e.occurred_date<=NULLIF($5::text,'')::date)
AND ($6::text='all' OR e.status=$6)
AND EXISTS(SELECT 1 FROM allocations l WHERE l.expense_id=e.id
 AND ($7::text='' OR l.category_id=$7)
 AND ($8::text='' OR l.project_id=$8))
AND e.status='posted' GROUP BY e.currency ORDER BY e.currency
`

type FilteredExpenseTotalsParams struct {
	AccountID    string
	Currency     string
	PaymentState string
	FromDate     string
	ToDate       string
	Status       string
	CategoryID   string
	ProjectID    string
}

type FilteredExpenseTotalsRow struct {
	Currency string
	Amount   string
}

func (q *Queries) FilteredExpenseTotals(ctx context.Context, arg FilteredExpenseTotalsParams) ([]FilteredExpenseTotalsRow, error) {
	rows, err := q.db.Query(ctx, filteredExpenseTotals,
		arg.AccountID,
		arg.Currency,
		arg.PaymentState,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.CategoryID,
		arg.ProjectID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilteredExpenseTotalsRow
	for rows.Next() {
		var i FilteredExpenseTotalsRow
		if err := rows.Scan(&i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredIncomeCount = `-- name: FilteredIncomeCount :one
SELECT count(*)
FROM incomes i JOIN accounts a ON a.id=i.account_id
WHERE ($1::text='' OR i.account_id=$1)
AND ($2::text='' OR a.currency=$2)
AND ($3::text='' OR i.occurred_date>=NULLIF($3::text,'')::date)
AND ($4::text='' OR i.occurred_date<=NULLIF($4::text,'')::date)
AND ($5::text='all' OR i.status=$5)
`

type FilteredIncomeCountParams struct {
	AccountID string
	Currency  string
	FromDate  string
	ToDate    string
	Status    string
}

func (q *Queries) FilteredIncomeCount(ctx context.Context, arg FilteredIncomeCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredIncomeCount,
		arg.AccountID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredIncomeIDs = `-- name: FilteredIncomeIDs :many
SELECT i.id
FROM incomes i JOIN accounts a ON a.id=i.account_id
WHERE ($1::text='' OR i.account_id=$1)
AND ($2::text='' OR a.currency=$2)
AND ($3::text='' OR i.occurred_date>=NULLIF($3::text,'')::date)
AND ($4::text='' OR i.occurred_date<=NULLIF($4::text,'')::date)
AND ($5::text='all' OR i.status=$5)
ORDER BY i.occurred_date DESC,i.id DESC LIMIT $7::bigint OFFSET $6::bigint
`

type FilteredIncomeIDsParams struct {
	AccountID  string
	Currency   string
	FromDate   string
	ToDate     string
	Status     string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) FilteredIncomeIDs(ctx context.Context, arg FilteredIncomeIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredIncomeIDs,
		arg.AccountID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredIncomeTotals = `-- name: FilteredIncomeTotals :many
SELECT a.currency,sum(i.amount_minor)::text AS amount
FROM incomes i JOIN accounts a ON a.id=i.account_id
WHERE ($1::text='' OR i.account_id=$1)
AND ($2::text='' OR a.currency=$2)
AND ($3::text='' OR i.occurred_date>=NULLIF($3::text,'')::date)
AND ($4::text='' OR i.occurred_date<=NULLIF($4::text,'')::date)
AND ($5::text='all' OR i.status=$5)
AND i.status='posted' GROUP BY a.currency ORDER BY a.currency
`

type FilteredIncomeTotalsParams struct {
	AccountID string
	Currency  string
	FromDate  string
	ToDate    string
	Status    string
}

type FilteredIncomeTotalsRow struct {
	Currency string
	Amount   string
}

func (q *Queries) FilteredIncomeTotals(ctx context.Context, arg FilteredIncomeTotalsParams) ([]FilteredIncomeTotalsRow, error) {
	rows, err := q.db.Query(ctx, filteredIncomeTotals,
		arg.AccountID,
		arg.Currency,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilteredIncomeTotalsRow
	for rows.Next() {
		var i FilteredIncomeTotalsRow
		if err := rows.Scan(&i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredReceivableCount = `-- name: FilteredReceivableCount :one
SELECT count(*) FROM receivables d LEFT JOIN (SELECT receivable_id,sum(amount_minor) amount FROM repayments WHERE status='posted' GROUP BY receivable_id) r ON r.receivable_id=d.id
WHERE ($1::text='' OR d.currency=$1) AND ($2::text='' OR d.debtor=$2) AND ($3::text='all' OR CASE WHEN d.status='void' THEN 'void' WHEN COALESCE(r.amount,0)=d.amount_minor THEN 'settled' ELSE 'open' END=$3)
`

type FilteredReceivableCountParams struct {
	Currency string
	Debtor   string
	Status   string
}

func (q *Queries) FilteredReceivableCount(ctx context.Context, arg FilteredReceivableCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredReceivableCount, arg.Currency, arg.Debtor, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredReceivableIDs = `-- name: FilteredReceivableIDs :many
SELECT d.id FROM receivables d LEFT JOIN (SELECT receivable_id,sum(amount_minor) amount FROM repayments WHERE status='posted' GROUP BY receivable_id) r ON r.receivable_id=d.id
WHERE ($1::text='' OR d.currency=$1) AND ($2::text='' OR d.debtor=$2) AND ($3::text='all' OR CASE WHEN d.status='void' THEN 'void' WHEN COALESCE(r.amount,0)=d.amount_minor THEN 'settled' ELSE 'open' END=$3) ORDER BY d.created_at DESC,d.id DESC LIMIT $5::bigint OFFSET $4::bigint
`

type FilteredReceivableIDsParams struct {
	Currency   string
	Debtor     string
	Status     string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) FilteredReceivableIDs(ctx context.Context, arg FilteredReceivableIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredReceivableIDs,
		arg.Currency,
		arg.Debtor,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredReceivableTotals = `-- name: FilteredReceivableTotals :many
SELECT d.currency,sum(d.amount_minor::numeric-COALESCE(r.amount,0))::text AS amount FROM receivables d LEFT JOIN (SELECT receivable_id,sum(amount_minor) amount FROM repayments WHERE status='posted' GROUP BY receivable_id) r ON r.receivable_id=d.id
WHERE ($1::text='' OR d.currency=$1) AND ($2::text='' OR d.debtor=$2) AND ($3::text='all' OR CASE WHEN d.status='void' THEN 'void' WHEN COALESCE(r.amount,0)=d.amount_minor THEN 'settled' ELSE 'open' END=$3) AND d.status='active' GROUP BY d.currency ORDER BY d.currency
`

type FilteredReceivableTotalsParams struct {
	Currency string
	Debtor   string
	Status   string
}

type FilteredReceivableTotalsRow struct {
	Currency string
	Amount   string
}

func (q *Queries) FilteredReceivableTotals(ctx context.Context, arg FilteredReceivableTotalsParams) ([]FilteredReceivableTotalsRow, error) {
	rows, err := q.db.Query(ctx, filteredReceivableTotals, arg.Currency, arg.Debtor, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilteredReceivableTotalsRow
	for rows.Next() {
		var i FilteredReceivableTotalsRow
		if err := rows.Scan(&i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredRepaymentCount = `-- name: FilteredRepaymentCount :one
SELECT count(*) FROM repayments r WHERE ($1::text='' OR r.receivable_id=$1) AND ($2::text='' OR r.account_id=$2) AND ($3::text='all' OR r.status=$3)
`

type FilteredRepaymentCountParams struct {
	ReceivableID string
	AccountID    string
	Status       string
}

func (q *Queries) FilteredRepaymentCount(ctx context.Context, arg FilteredRepaymentCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredRepaymentCount, arg.ReceivableID, arg.AccountID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredRepaymentIDs = `-- name: FilteredRepaymentIDs :many
SELECT r.id FROM repayments r WHERE ($1::text='' OR r.receivable_id=$1) AND ($2::text='' OR r.account_id=$2) AND ($3::text='all' OR r.status=$3) ORDER BY r.occurred_date DESC,r.id DESC LIMIT $5::bigint OFFSET $4::bigint
`

type FilteredRepaymentIDsParams struct {
	ReceivableID string
	AccountID    string
	Status       string
	PageOffset   int64
	PageLimit    int64
}

func (q *Queries) FilteredRepaymentIDs(ctx context.Context, arg FilteredRepaymentIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredRepaymentIDs,
		arg.ReceivableID,
		arg.AccountID,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filteredTransferCount = `-- name: FilteredTransferCount :one
SELECT count(*)
FROM transfers t
WHERE ($1::text='' OR t.source_account_id=$1 OR t.destination_account_id=$1)
AND ($2::text='' OR t.occurred_date>=NULLIF($2::text,'')::date)
AND ($3::text='' OR t.occurred_date<=NULLIF($3::text,'')::date)
AND ($4::text='all' OR t.status=$4)
`

type FilteredTransferCountParams struct {
	AccountID string
	FromDate  string
	ToDate    string
	Status    string
}

func (q *Queries) FilteredTransferCount(ctx context.Context, arg FilteredTransferCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, filteredTransferCount,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const filteredTransferIDs = `-- name: FilteredTransferIDs :many
SELECT t.id
FROM transfers t
WHERE ($1::text='' OR t.source_account_id=$1 OR t.destination_account_id=$1)
AND ($2::text='' OR t.occurred_date>=NULLIF($2::text,'')::date)
AND ($3::text='' OR t.occurred_date<=NULLIF($3::text,'')::date)
AND ($4::text='all' OR t.status=$4)
ORDER BY t.occurred_date DESC,t.id DESC LIMIT $6::bigint OFFSET $5::bigint
`

type FilteredTransferIDsParams struct {
	AccountID  string
	FromDate   string
	ToDate     string
	Status     string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) FilteredTransferIDs(ctx context.Context, arg FilteredTransferIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filteredTransferIDs,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
		arg.Status,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOperation = `-- name: GetOperation :one
SELECT operation, payload, result FROM operation_results WHERE operation_key=$1
`

type GetOperationRow struct {
	Operation string
	Payload   []byte
	Result    []byte
}

func (q *Queries) GetOperation(ctx context.Context, operationKey string) (GetOperationRow, error) {
	row := q.db.QueryRow(ctx, getOperation, operationKey)
	var i GetOperationRow
	err := row.Scan(&i.Operation, &i.Payload, &i.Result)
	return i, err
}

const hasPostedBalanceAdjustment = `-- name: HasPostedBalanceAdjustment :one
SELECT EXISTS(SELECT 1 FROM balance_adjustments WHERE observation_id=$1 AND status='posted')::boolean AS present
`

func (q *Queries) HasPostedBalanceAdjustment(ctx context.Context, observationID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPostedBalanceAdjustment, observationID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const insertAccount = `-- name: InsertAccount :exec
INSERT INTO accounts(id,name,currency,opening_minor,opening_date) VALUES($1,$2,$3,$4,$5::text::date)
`

type InsertAccountParams struct {
	ID           string
	Name         string
	Currency     string
	OpeningMinor int64
	Column5      string
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.OpeningMinor,
		arg.Column5,
	)
	return err
}

const insertAllocation = `-- name: InsertAllocation :exec
INSERT INTO allocations(expense_id,ordinal,amount_minor,category_id,project_id) VALUES($1,$2,$3,$4,NULLIF($5::text,''))
`

type InsertAllocationParams struct {
	ExpenseID   string
	Ordinal     int32
	AmountMinor int64
	CategoryID  string
	Column5     string
}

func (q *Queries) InsertAllocation(ctx context.Context, arg InsertAllocationParams) error {
	_, err := q.db.Exec(ctx, insertAllocation,
		arg.ExpenseID,
		arg.Ordinal,
		arg.AmountMinor,
		arg.CategoryID,
		arg.Column5,
	)
	return err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_entries(entity_id,action,snapshot,source,operation_key,request_id,client_name,client_version) VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertAuditParams struct {
	EntityID      string
	Action        string
	Snapshot      []byte
	Source        string
	OperationKey  string
	RequestID     string
	ClientName    string
	ClientVersion string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.EntityID,
		arg.Action,
		arg.Snapshot,
		arg.Source,
		arg.OperationKey,
		arg.RequestID,
		arg.ClientName,
		arg.ClientVersion,
	)
	return err
}

const insertBalanceAdjustment = `-- name: InsertBalanceAdjustment :exec
INSERT INTO balance_adjustments(id,observation_id,account_id,amount_minor,occurred_date,reason,version) VALUES($1,$2,$3,$4,$5::text::date,$6,1)
`

type InsertBalanceAdjustmentParams struct {
	ID            string
	ObservationID string
	AccountID     string
	AmountMinor   int64
	OccurredDate  string
	Reason        string
}

func (q *Queries) InsertBalanceAdjustment(ctx context.Context, arg InsertBalanceAdjustmentParams) error {
	_, err := q.db.Exec(ctx, insertBalanceAdjustment,
		arg.ID,
		arg.ObservationID,
		arg.AccountID,
		arg.AmountMinor,
		arg.OccurredDate,
		arg.Reason,
	)
	return err
}

const insertBuyingIntent = `-- name: InsertBuyingIntent :exec
INSERT INTO buying_intents(id,title,notes) VALUES($1,$2,$3)
`

type InsertBuyingIntentParams struct {
	ID    string
	Title string
	Notes string
}

func (q *Queries) InsertBuyingIntent(ctx context.Context, arg InsertBuyingIntentParams) error {
	_, err := q.db.Exec(ctx, insertBuyingIntent, arg.ID, arg.Title, arg.Notes)
	return err
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO categories(id,name) VALUES($1,$2)
`

type InsertCategoryParams struct {
	ID   string
	Name string
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.Exec(ctx, insertCategory, arg.ID, arg.Name)
	return err
}

const insertIntentCandidate = `-- name: InsertIntentCandidate :exec
INSERT INTO intent_candidates(id,intent_id,reference,notes,advertised_minor,currency) VALUES($1,$2,$3,$4,$5,$6)
`

type InsertIntentCandidateParams struct {
	ID              string
	IntentID        string
	Reference       string
	Notes           string
	AdvertisedMinor pgtype.Int8
	Currency        pgtype.Text
}

func (q *Queries) InsertIntentCandidate(ctx context.Context, arg InsertIntentCandidateParams) error {
	_, err := q.db.Exec(ctx, insertIntentCandidate,
		arg.ID,
		arg.IntentID,
		arg.Reference,
		arg.Notes,
		arg.AdvertisedMinor,
		arg.Currency,
	)
	return err
}

const insertProject = `-- name: InsertProject :exec
INSERT INTO projects(id,name) VALUES($1,$2)
`

type InsertProjectParams struct {
	ID   string
	Name string
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) error {
	_, err := q.db.Exec(ctx, insertProject, arg.ID, arg.Name)
	return err
}

const listBuyingIntentIDs = `-- name: ListBuyingIntentIDs :many
SELECT id FROM buying_intents WHERE ($1::text='all' OR status=$1::text) AND ($2::text='' OR strpos(lower(title),lower($2::text))>0 OR strpos(lower(notes),lower($2::text))>0) ORDER BY created_at DESC,id DESC LIMIT $4::bigint OFFSET $3::bigint
`

type ListBuyingIntentIDsParams struct {
	Status     string
	Search     string
	PageOffset int64
	PageLimit  int64
}

func (q *Queries) ListBuyingIntentIDs(ctx context.Context, arg ListBuyingIntentIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listBuyingIntentIDs,
		arg.Status,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntentCandidates = `-- name: ListIntentCandidates :many
SELECT id,reference,notes,advertised_minor,coalesce(currency,'')::text AS currency FROM intent_candidates WHERE intent_id=$1 ORDER BY created_at,id
`

type ListIntentCandidatesRow struct {
	ID              string
	Reference       string
	Notes           string
	AdvertisedMinor pgtype.Int8
	Currency        string
}

func (q *Queries) ListIntentCandidates(ctx context.Context, intentID string) ([]ListIntentCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listIntentCandidates, intentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntentCandidatesRow
	for rows.Next() {
		var i ListIntentCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Reference,
			&i.Notes,
			&i.AdvertisedMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccount = `-- name: LockAccount :one
SELECT currency,opening_date::text,version,archived FROM accounts WHERE id=$1 FOR UPDATE
`

type LockAccountRow struct {
	Currency    string
	OpeningDate string
	Version     int64
	Archived    bool
}

func (q *Queries) LockAccount(ctx context.Context, id string) (LockAccountRow, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var i LockAccountRow
	err := row.Scan(
		&i.Currency,
		&i.OpeningDate,
		&i.Version,
		&i.Archived,
	)
	return i, err
}

const lockBalanceAdjustment = `-- name: LockBalanceAdjustment :one
SELECT version,status FROM balance_adjustments WHERE id=$1 FOR UPDATE
`

type LockBalanceAdjustmentRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockBalanceAdjustment(ctx context.Context, id string) (LockBalanceAdjustmentRow, error) {
	row := q.db.QueryRow(ctx, lockBalanceAdjustment, id)
	var i LockBalanceAdjustmentRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockBalanceObservation = `-- name: LockBalanceObservation :one
SELECT version,status FROM balance_observations WHERE id=$1 FOR UPDATE
`

type LockBalanceObservationRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockBalanceObservation(ctx context.Context, id string) (LockBalanceObservationRow, error) {
	row := q.db.QueryRow(ctx, lockBalanceObservation, id)
	var i LockBalanceObservationRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockBuyingIntent = `-- name: LockBuyingIntent :one
SELECT version,status FROM buying_intents WHERE id=$1 FOR UPDATE
`

type LockBuyingIntentRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockBuyingIntent(ctx context.Context, id string) (LockBuyingIntentRow, error) {
	row := q.db.QueryRow(ctx, lockBuyingIntent, id)
	var i LockBuyingIntentRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockCategory = `-- name: LockCategory :one
SELECT id,name,version,archived FROM categories WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockCategory(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRow(ctx, lockCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Archived,
	)
	return i, err
}

const lockExpense = `-- name: LockExpense :one
SELECT version,status FROM expenses WHERE id=$1 FOR UPDATE
`

type LockExpenseRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockExpense(ctx context.Context, id string) (LockExpenseRow, error) {
	row := q.db.QueryRow(ctx, lockExpense, id)
	var i LockExpenseRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockIncome = `-- name: LockIncome :one
SELECT version,status FROM incomes WHERE id=$1 FOR UPDATE
`

type LockIncomeRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockIncome(ctx context.Context, id string) (LockIncomeRow, error) {
	row := q.db.QueryRow(ctx, lockIncome, id)
	var i LockIncomeRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockProject = `-- name: LockProject :one
SELECT id,name,version,archived FROM projects WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, lockProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Archived,
	)
	return i, err
}

const lockReceivable = `-- name: LockReceivable :one
SELECT version,status FROM receivables WHERE id=$1 FOR UPDATE
`

type LockReceivableRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockReceivable(ctx context.Context, id string) (LockReceivableRow, error) {
	row := q.db.QueryRow(ctx, lockReceivable, id)
	var i LockReceivableRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const lockRepayment = `-- name: LockRepayment :one
SELECT version,status,receivable_id,amount_minor FROM repayments WHERE id=$1 FOR UPDATE
`

type LockRepaymentRow struct {
	Version      int64
	Status       string
	ReceivableID string
	AmountMinor  int64
}

func (q *Queries) LockRepayment(ctx context.Context, id string) (LockRepaymentRow, error) {
	row := q.db.QueryRow(ctx, lockRepayment, id)
	var i LockRepaymentRow
	err := row.Scan(
		&i.Version,
		&i.Status,
		&i.ReceivableID,
		&i.AmountMinor,
	)
	return i, err
}

const lockTransfer = `-- name: LockTransfer :one
SELECT version,status FROM transfers WHERE id=$1 FOR UPDATE
`

type LockTransferRow struct {
	Version int64
	Status  string
}

func (q *Queries) LockTransfer(ctx context.Context, id string) (LockTransferRow, error) {
	row := q.db.QueryRow(ctx, lockTransfer, id)
	var i LockTransferRow
	err := row.Scan(&i.Version, &i.Status)
	return i, err
}

const monthlyAccountMovements = `-- name: MonthlyAccountMovements :many
WITH movement AS (
 SELECT account_id,'expense'::text AS kind,debit_minor::numeric AS amount,debit_state FROM expenses WHERE status='posted' AND occurred_date>=$3::text::date AND occurred_date<=$1::text::date
 UNION ALL SELECT account_id,'income',amount_minor::numeric,'exact' FROM incomes WHERE status='posted' AND occurred_date>=$3::text::date AND occurred_date<=$1::text::date
 UNION ALL SELECT source_account_id,'transfer_out',source_minor::numeric,'exact' FROM transfers WHERE status='posted' AND occurred_date>=$3::text::date AND occurred_date<=$1::text::date
 UNION ALL SELECT destination_account_id,'transfer_in',destination_minor::numeric,'exact' FROM transfers WHERE status='posted' AND occurred_date>=$3::text::date AND occurred_date<=$1::text::date
 UNION ALL SELECT account_id,'repayment',amount_minor::numeric,'exact' FROM repayments WHERE status='posted' AND occurred_date>=$3::text::date AND occurred_date<=$1::text::date
 UNION ALL SELECT account_id,'adjustment',amount_minor::numeric,'exact' FROM balance_adjustments WHERE status='posted' AND occurred_date>=$3::text::date AND occurred_date<=$1::text::date
)
SELECT a.id,a.name,a.currency,
 COALESCE(sum(m.amount) FILTER(WHERE m.kind='expense'),0)::text AS expense_debits,
 COALESCE(sum(m.amount) FILTER(WHERE m.kind='income'),0)::text AS income,
 COALESCE(sum(m.amount) FILTER(WHERE m.kind='transfer_in'),0)::text AS transfer_in,
 COALESCE(sum(m.amount) FILTER(WHERE m.kind='transfer_out'),0)::text AS transfer_out,
 COALESCE(sum(m.amount) FILTER(WHERE m.kind='repayment'),0)::text AS repayments,
 COALESCE(sum(m.amount) FILTER(WHERE m.kind='adjustment'),0)::text AS adjustments,
 COALESCE(sum(CASE WHEN m.kind IN ('expense','transfer_out') THEN -m.amount ELSE m.amount END),0)::text AS net_change,
 count(*) FILTER(WHERE m.debit_state='estimated') AS estimated_count,
 count(*) FILTER(WHERE m.debit_state='unresolved') AS unresolved_count
 FROM accounts a LEFT JOIN movement m ON m.account_id=a.id
 WHERE a.opening_date<=$1::text::date AND ($2::text='' OR a.id=$2)
 GROUP BY a.id,a.name,a.currency ORDER BY a.name,a.id
`

type MonthlyAccountMovementsParams struct {
	ToDate    string
	AccountID string
	FromDate  string
}

type MonthlyAccountMovementsRow struct {
	ID              string
	Name            string
	Currency        string
	ExpenseDebits   string
	Income          string
	TransferIn      string
	TransferOut     string
	Repayments      string
	Adjustments     string
	NetChange       string
	EstimatedCount  int64
	UnresolvedCount int64
}

func (q *Queries) MonthlyAccountMovements(ctx context.Context, arg MonthlyAccountMovementsParams) ([]MonthlyAccountMovementsRow, error) {
	rows, err := q.db.Query(ctx, monthlyAccountMovements, arg.ToDate, arg.AccountID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyAccountMovementsRow
	for rows.Next() {
		var i MonthlyAccountMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.ExpenseDebits,
			&i.Income,
			&i.TransferIn,
			&i.TransferOut,
			&i.Repayments,
			&i.Adjustments,
			&i.NetChange,
			&i.EstimatedCount,
			&i.UnresolvedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyCategoryTotals = `-- name: MonthlyCategoryTotals :many
SELECT c.id,c.name,e.currency,sum(l.amount_minor)::text AS amount FROM allocations l JOIN expenses e ON e.id=l.expense_id JOIN categories c ON c.id=l.category_id WHERE e.status='posted' AND e.occurred_date>=$1::text::date AND e.occurred_date<=$2::text::date AND ($3::text='' OR e.account_id=$3) GROUP BY c.id,c.name,e.currency ORDER BY c.name,c.id,e.currency
`

type MonthlyCategoryTotalsParams struct {
	FromDate  string
	ToDate    string
	AccountID string
}

type MonthlyCategoryTotalsRow struct {
	ID       string
	Name     string
	Currency string
	Amount   string
}

func (q *Queries) MonthlyCategoryTotals(ctx context.Context, arg MonthlyCategoryTotalsParams) ([]MonthlyCategoryTotalsRow, error) {
	rows, err := q.db.Query(ctx, monthlyCategoryTotals, arg.FromDate, arg.ToDate, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyCategoryTotalsRow
	for rows.Next() {
		var i MonthlyCategoryTotalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyIncomeTotals = `-- name: MonthlyIncomeTotals :many
SELECT a.currency,sum(i.amount_minor)::text AS amount FROM incomes i JOIN accounts a ON a.id=i.account_id WHERE i.status='posted' AND i.occurred_date>=$1::text::date AND i.occurred_date<=$2::text::date AND ($3::text='' OR i.account_id=$3) GROUP BY a.currency ORDER BY a.currency
`

type MonthlyIncomeTotalsParams struct {
	FromDate  string
	ToDate    string
	AccountID string
}

type MonthlyIncomeTotalsRow struct {
	Currency string
	Amount   string
}

func (q *Queries) MonthlyIncomeTotals(ctx context.Context, arg MonthlyIncomeTotalsParams) ([]MonthlyIncomeTotalsRow, error) {
	rows, err := q.db.Query(ctx, monthlyIncomeTotals, arg.FromDate, arg.ToDate, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyIncomeTotalsRow
	for rows.Next() {
		var i MonthlyIncomeTotalsRow
		if err := rows.Scan(&i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyProjectTotals = `-- name: MonthlyProjectTotals :many
SELECT COALESCE(p.id,'')::text AS id,COALESCE(p.name,'')::text AS name,e.currency,sum(l.amount_minor)::text AS amount FROM allocations l JOIN expenses e ON e.id=l.expense_id LEFT JOIN projects p ON p.id=l.project_id WHERE e.status='posted' AND e.occurred_date>=$1::text::date AND e.occurred_date<=$2::text::date AND ($3::text='' OR e.account_id=$3) GROUP BY p.id,p.name,e.currency ORDER BY p.name NULLS FIRST,p.id,e.currency
`

type MonthlyProjectTotalsParams struct {
	FromDate  string
	ToDate    string
	AccountID string
}

type MonthlyProjectTotalsRow struct {
	ID       string
	Name     string
	Currency string
	Amount   string
}

func (q *Queries) MonthlyProjectTotals(ctx context.Context, arg MonthlyProjectTotalsParams) ([]MonthlyProjectTotalsRow, error) {
	rows, err := q.db.Query(ctx, monthlyProjectTotals, arg.FromDate, arg.ToDate, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyProjectTotalsRow
	for rows.Next() {
		var i MonthlyProjectTotalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlySpendingTotals = `-- name: MonthlySpendingTotals :many
SELECT e.currency,sum(e.amount_minor)::text AS amount FROM expenses e WHERE e.status='posted' AND e.occurred_date>=$1::text::date AND e.occurred_date<=$2::text::date AND ($3::text='' OR e.account_id=$3) GROUP BY e.currency ORDER BY e.currency
`

type MonthlySpendingTotalsParams struct {
	FromDate  string
	ToDate    string
	AccountID string
}

type MonthlySpendingTotalsRow struct {
	Currency string
	Amount   string
}

func (q *Queries) MonthlySpendingTotals(ctx context.Context, arg MonthlySpendingTotalsParams) ([]MonthlySpendingTotalsRow, error) {
	rows, err := q.db.Query(ctx, monthlySpendingTotals, arg.FromDate, arg.ToDate, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlySpendingTotalsRow
	for rows.Next() {
		var i MonthlySpendingTotalsRow
		if err := rows.Scan(&i.Currency, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSpending = `-- name: ProjectSpending :many
SELECT p.id,p.name,e.currency,sum(l.amount_minor)::text AS amount FROM allocations l JOIN expenses e ON e.id=l.expense_id JOIN accounts a ON a.id=e.account_id JOIN projects p ON p.id=l.project_id WHERE e.status='posted' GROUP BY p.id,e.currency ORDER BY p.name,e.currency
`

type ProjectSpendingRow struct {
	ID       string
	Name     string
	Currency string
	Amount   string
}

func (q *Queries) ProjectSpending(ctx context.Context) ([]ProjectSpendingRow, error) {
	rows, err := q.db.Query(ctx, projectSpending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectSpendingRow
	for rows.Next() {
		var i ProjectSpendingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projects = `-- name: Projects :many
SELECT id,name,version,archived FROM projects ORDER BY name,id
`

func (q *Queries) Projects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, projects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purchaseBuyingIntent = `-- name: PurchaseBuyingIntent :exec
UPDATE buying_intents SET status='purchased',outcome_note=$2,candidate_id=nullif($3,''),expense_id=$4,version=version+1 WHERE id=$1
`

type PurchaseBuyingIntentParams struct {
	ID          string
	OutcomeNote string
	Column3     interface{}
	ExpenseID   pgtype.Text
}

func (q *Queries) PurchaseBuyingIntent(ctx context.Context, arg PurchaseBuyingIntentParams) error {
	_, err := q.db.Exec(ctx, purchaseBuyingIntent,
		arg.ID,
		arg.OutcomeNote,
		arg.Column3,
		arg.ExpenseID,
	)
	return err
}

const readAllocations = `-- name: ReadAllocations :many
SELECT amount_minor,category_id,COALESCE(project_id,'')::text AS project_id FROM allocations WHERE expense_id=$1 ORDER BY ordinal
`

type ReadAllocationsRow struct {
	AmountMinor int64
	CategoryID  string
	ProjectID   string
}

func (q *Queries) ReadAllocations(ctx context.Context, expenseID string) ([]ReadAllocationsRow, error) {
	rows, err := q.db.Query(ctx, readAllocations, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadAllocationsRow
	for rows.Next() {
		var i ReadAllocationsRow
		if err := rows.Scan(&i.AmountMinor, &i.CategoryID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readBalanceAdjustment = `-- name: ReadBalanceAdjustment :one
SELECT b.id,b.observation_id,b.account_id,a.currency,b.amount_minor,b.occurred_date::text AS occurred_date,b.reason,b.status,b.version FROM balance_adjustments b JOIN accounts a ON a.id=b.account_id WHERE b.id=$1
`

type ReadBalanceAdjustmentRow struct {
	ID            string
	ObservationID string
	AccountID     string
	Currency      string
	AmountMinor   int64
	OccurredDate  string
	Reason        string
	Status        string
	Version       int64
}

func (q *Queries) ReadBalanceAdjustment(ctx context.Context, id string) (ReadBalanceAdjustmentRow, error) {
	row := q.db.QueryRow(ctx, readBalanceAdjustment, id)
	var i ReadBalanceAdjustmentRow
	err := row.Scan(
		&i.ID,
		&i.ObservationID,
		&i.AccountID,
		&i.Currency,
		&i.AmountMinor,
		&i.OccurredDate,
		&i.Reason,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const readBalanceObservation = `-- name: ReadBalanceObservation :one
SELECT o.id,o.account_id,a.currency,o.as_of_date::text AS as_of_date,o.actual_minor,o.recorded_ledger_minor::text AS recorded_ledger_minor,o.basis,o.notes,o.status,o.version FROM balance_observations o JOIN accounts a ON a.id=o.account_id WHERE o.id=$1
`

type ReadBalanceObservationRow struct {
	ID                  string
	AccountID           string
	Currency            string
	AsOfDate            string
	ActualMinor         int64
	RecordedLedgerMinor string
	Basis               string
	Notes               string
	Status              string
	Version             int64
}

func (q *Queries) ReadBalanceObservation(ctx context.Context, id string) (ReadBalanceObservationRow, error) {
	row := q.db.QueryRow(ctx, readBalanceObservation, id)
	var i ReadBalanceObservationRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Currency,
		&i.AsOfDate,
		&i.ActualMinor,
		&i.RecordedLedgerMinor,
		&i.Basis,
		&i.Notes,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const readBuyingIntent = `-- name: ReadBuyingIntent :one
SELECT id,title,notes,status,version,coalesce(candidate_id,'')::text AS candidate_id,outcome_note,coalesce(expense_id,'')::text AS expense_id FROM buying_intents WHERE id=$1
`

type ReadBuyingIntentRow struct {
	ID          string
	Title       string
	Notes       string
	Status      string
	Version     int64
	CandidateID string
	OutcomeNote string
	ExpenseID   string
}

func (q *Queries) ReadBuyingIntent(ctx context.Context, id string) (ReadBuyingIntentRow, error) {
	row := q.db.QueryRow(ctx, readBuyingIntent, id)
	var i ReadBuyingIntentRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Status,
		&i.Version,
		&i.CandidateID,
		&i.OutcomeNote,
		&i.ExpenseID,
	)
	return i, err
}

const readExpense = `-- name: ReadExpense :one
SELECT e.id,e.account_id,e.amount_minor,e.currency,a.currency AS debit_currency,e.debit_minor,e.debit_state,e.conversion_evidence,e.occurred_date::text AS occurred_date,e.description,e.status,e.version FROM expenses e JOIN accounts a ON a.id=e.account_id WHERE e.id=$1
`

type ReadExpenseRow struct {
	ID                 string
	AccountID          string
	AmountMinor        int64
	Currency           string
	DebitCurrency      string
	DebitMinor         pgtype.Int8
	DebitState         string
	ConversionEvidence []byte
	OccurredDate       string
	Description        string
	Status             string
	Version            int64
}

func (q *Queries) ReadExpense(ctx context.Context, id string) (ReadExpenseRow, error) {
	row := q.db.QueryRow(ctx, readExpense, id)
	var i ReadExpenseRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.DebitCurrency,
		&i.DebitMinor,
		&i.DebitState,
		&i.ConversionEvidence,
		&i.OccurredDate,
		&i.Description,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const readIncome = `-- name: ReadIncome :one
SELECT i.id,i.account_id,i.amount_minor,a.currency,i.occurred_date::text AS occurred_date,i.description,i.status,i.version FROM incomes i JOIN accounts a ON a.id=i.account_id WHERE i.id=$1
`

type ReadIncomeRow struct {
	ID           string
	AccountID    string
	AmountMinor  int64
	Currency     string
	OccurredDate string
	Description  string
	Status       string
	Version      int64
}

func (q *Queries) ReadIncome(ctx context.Context, id string) (ReadIncomeRow, error) {
	row := q.db.QueryRow(ctx, readIncome, id)
	var i ReadIncomeRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.AmountMinor,
		&i.Currency,
		&i.OccurredDate,
		&i.Description,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const readProject = `-- name: ReadProject :one
SELECT id,name,version,archived FROM projects WHERE id=$1
`

func (q *Queries) ReadProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, readProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Archived,
	)
	return i, err
}

const readReceivable = `-- name: ReadReceivable :one
SELECT d.id,d.debtor,d.amount_minor,d.currency,COALESCE(d.due_date::text,'')::text AS due_date,d.notes,d.version,CASE WHEN d.status='void' THEN 'void' WHEN COALESCE(r.amount,0)=d.amount_minor THEN 'settled' ELSE 'open' END::text AS status,COALESCE(r.amount,0)::text AS repaid FROM receivables d LEFT JOIN (SELECT receivable_id,sum(amount_minor) amount FROM repayments WHERE status='posted' GROUP BY receivable_id) r ON r.receivable_id=d.id WHERE d.id=$1
`

type ReadReceivableRow struct {
	ID          string
	Debtor      string
	AmountMinor int64
	Currency    string
	DueDate     string
	Notes       string
	Version     int64
	Status      string
	Repaid      string
}

func (q *Queries) ReadReceivable(ctx context.Context, id string) (ReadReceivableRow, error) {
	row := q.db.QueryRow(ctx, readReceivable, id)
	var i ReadReceivableRow
	err := row.Scan(
		&i.ID,
		&i.Debtor,
		&i.AmountMinor,
		&i.Currency,
		&i.DueDate,
		&i.Notes,
		&i.Version,
		&i.Status,
		&i.Repaid,
	)
	return i, err
}

const readRepayment = `-- name: ReadRepayment :one
SELECT r.id,r.receivable_id,r.account_id,a.currency,r.amount_minor,r.occurred_date::text AS occurred_date,r.description,r.status,r.version FROM repayments r JOIN accounts a ON a.id=r.account_id WHERE r.id=$1
`

type ReadRepaymentRow struct {
	ID           string
	ReceivableID string
	AccountID    string
	Currency     string
	AmountMinor  int64
	OccurredDate string
	Description  string
	Status       string
	Version      int64
}

func (q *Queries) ReadRepayment(ctx context.Context, id string) (ReadRepaymentRow, error) {
	row := q.db.QueryRow(ctx, readRepayment, id)
	var i ReadRepaymentRow
	err := row.Scan(
		&i.ID,
		&i.ReceivableID,
		&i.AccountID,
		&i.Currency,
		&i.AmountMinor,
		&i.OccurredDate,
		&i.Description,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const readTransfer = `-- name: ReadTransfer :one
SELECT t.id,t.source_account_id,t.destination_account_id,t.source_minor,t.destination_minor,s.currency AS source_currency,d.currency AS destination_currency,t.occurred_date::text AS occurred_date,t.description,t.status,t.version FROM transfers t JOIN accounts s ON s.id=t.source_account_id JOIN accounts d ON d.id=t.destination_account_id WHERE t.id=$1
`

type ReadTransferRow struct {
	ID                   string
	SourceAccountID      string
	DestinationAccountID string
	SourceMinor          int64
	DestinationMinor     int64
	SourceCurrency       string
	DestinationCurrency  string
	OccurredDate         string
	Description          string
	Status               string
	Version              int64
}

func (q *Queries) ReadTransfer(ctx context.Context, id string) (ReadTransferRow, error) {
	row := q.db.QueryRow(ctx, readTransfer, id)
	var i ReadTransferRow
	err := row.Scan(
		&i.ID,
		&i.SourceAccountID,
		&i.DestinationAccountID,
		&i.SourceMinor,
		&i.DestinationMinor,
		&i.SourceCurrency,
		&i.DestinationCurrency,
		&i.OccurredDate,
		&i.Description,
		&i.Status,
		&i.Version,
	)
	return i, err
}

const recentExpenseIDs = `-- name: RecentExpenseIDs :many
SELECT id FROM expenses ORDER BY occurred_date DESC,id DESC LIMIT 100
`

func (q *Queries) RecentExpenseIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, recentExpenseIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOperation = `-- name: SaveOperation :exec
INSERT INTO operation_results(operation_key,operation,payload,result) VALUES($1,$2,$3,$4)
`

type SaveOperationParams struct {
	OperationKey string
	Operation    string
	Payload      []byte
	Result       []byte
}

func (q *Queries) SaveOperation(ctx context.Context, arg SaveOperationParams) error {
	_, err := q.db.Exec(ctx, saveOperation,
		arg.OperationKey,
		arg.Operation,
		arg.Payload,
		arg.Result,
	)
	return err
}

const updateAccountLifecycle = `-- name: UpdateAccountLifecycle :exec
UPDATE accounts SET name=$2,archived=$3,version=version+1 WHERE id=$1
`

type UpdateAccountLifecycleParams struct {
	ID       string
	Name     string
	Archived bool
}

func (q *Queries) UpdateAccountLifecycle(ctx context.Context, arg UpdateAccountLifecycleParams) error {
	_, err := q.db.Exec(ctx, updateAccountLifecycle, arg.ID, arg.Name, arg.Archived)
	return err
}

const updateBuyingIntent = `-- name: UpdateBuyingIntent :exec
UPDATE buying_intents SET title=$2,notes=$3,version=version+1 WHERE id=$1
`

type UpdateBuyingIntentParams struct {
	ID    string
	Title string
	Notes string
}

func (q *Queries) UpdateBuyingIntent(ctx context.Context, arg UpdateBuyingIntentParams) error {
	_, err := q.db.Exec(ctx, updateBuyingIntent, arg.ID, arg.Title, arg.Notes)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name=$2,archived=$3,version=version+1 WHERE id=$1
`

type UpdateCategoryParams struct {
	ID       string
	Name     string
	Archived bool
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, updateCategory, arg.ID, arg.Name, arg.Archived)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects SET name=$2,archived=$3,version=version+1 WHERE id=$1
`

type UpdateProjectParams struct {
	ID       string
	Name     string
	Archived bool
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.Exec(ctx, updateProject, arg.ID, arg.Name, arg.Archived)
	return err
}

const upsertBalanceObservation = `-- name: UpsertBalanceObservation :exec
INSERT INTO balance_observations(id,account_id,as_of_date,actual_minor,recorded_ledger_minor,basis,notes,version) VALUES($1,$2,$3::text::date,$4,$5::text::numeric,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,as_of_date=excluded.as_of_date,actual_minor=excluded.actual_minor,recorded_ledger_minor=excluded.recorded_ledger_minor,basis=excluded.basis,notes=excluded.notes,version=excluded.version
`

type UpsertBalanceObservationParams struct {
	ID                  string
	AccountID           string
	AsOfDate            string
	ActualMinor         int64
	RecordedLedgerMinor string
	Basis               string
	Notes               string
	Version             int64
}

func (q *Queries) UpsertBalanceObservation(ctx context.Context, arg UpsertBalanceObservationParams) error {
	_, err := q.db.Exec(ctx, upsertBalanceObservation,
		arg.ID,
		arg.AccountID,
		arg.AsOfDate,
		arg.ActualMinor,
		arg.RecordedLedgerMinor,
		arg.Basis,
		arg.Notes,
		arg.Version,
	)
	return err
}

const upsertExpense = `-- name: UpsertExpense :exec
INSERT INTO expenses(id,account_id,amount_minor,occurred_date,description,version,status,currency,debit_minor,debit_state,conversion_evidence) VALUES($1,$2,$3,$4::text::date,$5,$6,'posted',$7,$8,$9,$10) ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,amount_minor=excluded.amount_minor,occurred_date=excluded.occurred_date,description=excluded.description,version=excluded.version,currency=excluded.currency,debit_minor=excluded.debit_minor,debit_state=excluded.debit_state,conversion_evidence=excluded.conversion_evidence
`

type UpsertExpenseParams struct {
	ID                 string
	AccountID          string
	AmountMinor        int64
	OccurredDate       string
	Description        string
	Version            int64
	Currency           string
	DebitMinor         pgtype.Int8
	DebitState         string
	ConversionEvidence []byte
}

func (q *Queries) UpsertExpense(ctx context.Context, arg UpsertExpenseParams) error {
	_, err := q.db.Exec(ctx, upsertExpense,
		arg.ID,
		arg.AccountID,
		arg.AmountMinor,
		arg.OccurredDate,
		arg.Description,
		arg.Version,
		arg.Currency,
		arg.DebitMinor,
		arg.DebitState,
		arg.ConversionEvidence,
	)
	return err
}

const upsertIncome = `-- name: UpsertIncome :exec
INSERT INTO incomes(id,account_id,amount_minor,occurred_date,description,version,status) VALUES($1,$2,$3,$4::text::date,$5,$6,'posted') ON CONFLICT(id) DO UPDATE SET account_id=excluded.account_id,amount_minor=excluded.amount_minor,occurred_date=excluded.occurred_date,description=excluded.description,version=excluded.version
`

type UpsertIncomeParams struct {
	ID          string
	AccountID   string
	AmountMinor int64
	Column4     string
	Description string
	Version     int64
}

func (q *Queries) UpsertIncome(ctx context.Context, arg UpsertIncomeParams) error {
	_, err := q.db.Exec(ctx, upsertIncome,
		arg.ID,
		arg.AccountID,
		arg.AmountMinor,
		arg.Column4,
		arg.Description,
		arg.Version,
	)
	return err
}

const upsertReceivable = `-- name: UpsertReceivable :exec
INSERT INTO receivables(id,debtor,amount_minor,currency,due_date,notes,version,status) VALUES($1,$2,$3,$4,NULLIF($5::text,'')::date,$6,$7,'active') ON CONFLICT(id) DO UPDATE SET debtor=EXCLUDED.debtor,amount_minor=EXCLUDED.amount_minor,currency=EXCLUDED.currency,due_date=EXCLUDED.due_date,notes=EXCLUDED.notes,version=EXCLUDED.version
`

type UpsertReceivableParams struct {
	ID          string
	Debtor      string
	AmountMinor int64
	Currency    string
	DueDate     string
	Notes       string
	Version     int64
}

func (q *Queries) UpsertReceivable(ctx context.Context, arg UpsertReceivableParams) error {
	_, err := q.db.Exec(ctx, upsertReceivable,
		arg.ID,
		arg.Debtor,
		arg.AmountMinor,
		arg.Currency,
		arg.DueDate,
		arg.Notes,
		arg.Version,
	)
	return err
}

const upsertRepayment = `-- name: UpsertRepayment :exec
INSERT INTO repayments(id,receivable_id,account_id,amount_minor,occurred_date,description,version,status) VALUES($1,$2,$3,$4,$5::text::date,$6,$7,'posted') ON CONFLICT(id) DO UPDATE SET account_id=EXCLUDED.account_id,amount_minor=EXCLUDED.amount_minor,occurred_date=EXCLUDED.occurred_date,description=EXCLUDED.description,version=EXCLUDED.version
`

type UpsertRepaymentParams struct {
	ID           string
	ReceivableID string
	AccountID    string
	AmountMinor  int64
	OccurredDate string
	Description  string
	Version      int64
}

func (q *Queries) UpsertRepayment(ctx context.Context, arg UpsertRepaymentParams) error {
	_, err := q.db.Exec(ctx, upsertRepayment,
		arg.ID,
		arg.ReceivableID,
		arg.AccountID,
		arg.AmountMinor,
		arg.OccurredDate,
		arg.Description,
		arg.Version,
	)
	return err
}

const upsertTransfer = `-- name: UpsertTransfer :exec
INSERT INTO transfers(id,source_account_id,destination_account_id,source_minor,destination_minor,occurred_date,description,version,status) VALUES($1,$2,$3,$4,$5,$6::text::date,$7,$8,'posted') ON CONFLICT(id) DO UPDATE SET source_account_id=excluded.source_account_id,destination_account_id=excluded.destination_account_id,source_minor=excluded.source_minor,destination_minor=excluded.destination_minor,occurred_date=excluded.occurred_date,description=excluded.description,version=excluded.version
`

type UpsertTransferParams struct {
	ID                   string
	SourceAccountID      string
	DestinationAccountID string
	SourceMinor          int64
	DestinationMinor     int64
	Column6              string
	Description          string
	Version              int64
}

func (q *Queries) UpsertTransfer(ctx context.Context, arg UpsertTransferParams) error {
	_, err := q.db.Exec(ctx, upsertTransfer,
		arg.ID,
		arg.SourceAccountID,
		arg.DestinationAccountID,
		arg.SourceMinor,
		arg.DestinationMinor,
		arg.Column6,
		arg.Description,
		arg.Version,
	)
	return err
}

const voidBalanceAdjustment = `-- name: VoidBalanceAdjustment :exec
UPDATE balance_adjustments SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidBalanceAdjustment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidBalanceAdjustment, id)
	return err
}

const voidBalanceObservation = `-- name: VoidBalanceObservation :exec
UPDATE balance_observations SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidBalanceObservation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidBalanceObservation, id)
	return err
}

const voidExpense = `-- name: VoidExpense :exec
UPDATE expenses SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidExpense(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidExpense, id)
	return err
}

const voidIncome = `-- name: VoidIncome :exec
UPDATE incomes SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidIncome(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidIncome, id)
	return err
}

const voidReceivable = `-- name: VoidReceivable :exec
UPDATE receivables SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidReceivable(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidReceivable, id)
	return err
}

const voidRepayment = `-- name: VoidRepayment :exec
UPDATE repayments SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidRepayment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidRepayment, id)
	return err
}

const voidTransfer = `-- name: VoidTransfer :exec
UPDATE transfers SET status='void',version=version+1 WHERE id=$1
`

func (q *Queries) VoidTransfer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, voidTransfer, id)
	return err
}
